[package]
name = "adventofcode-2022"
version = "0.1.0"
description = "Advent of Code puzzles, 2022 edition."
edition = "2021"

[dependencies]

[[bin]]
name = "day01"
path = "src/day01.rs"

[[bin]]
name = "day02"
path = "src/day02.rs"